### ISSUE TITLE
where can I find the v1 docs?

### ISSUE THREAD

**Issue by shazron** [oclif/oclif.github.io#143]
Normally if docs are updated, the previous version is kept accessible, not everyone can upgrade within a short time frame, and will need to refer to the v1 docs in the meantime. 

I understand that the website wasn't designed for multiple versions so that is fine.

I can refer to the v1 docs from a tag, but I can't find any tags in this repo.

**Comment by hectorvp** [comment]
Did anyone found a  simplified way to refer v1 docs? I tried to add a tag and run this website but seems it is using some  native-node modules which failed at `npm install`

**Comment by shazron** [comment]
This worked for me, even `npm install` (i'm in macOS):
```
git clone https://github.com/oclif/oclif.github.io
cd oclif.github.io/website
git checkout -b v1-docs c5161bc7cf76d23ddd16ac05b6c7b2725069510
npm install
npm start
```
