### ISSUE TITLE
Building your own plugin documentation bug

### ISSUE THREAD

**Issue by swinton** [oclif/oclif.github.io#151]
The [documentation on building your own plugin](https://oclif.io/docs/plugins#building-your-own-plugin) appears to be incorrect:

Specifically:

> Run `npx oclif plugin mynewplugin` to create a plugin in a new directory. This will come with a sample command called `hello`.

The command `npx oclif plugin mynewplugin` did not work for me, I get the error message:

```
Warning: plugin mynewplugin is not a oclif command.
```

**Comment by mdonnalley** [comment]
Docs have been updated since you created this issue - I think it's good now so I'm going to close this issue. Feel free to open a new one if something is still wrong.
