### ISSUE TITLE
Custom Base Command class: 'flags' does not exist on type 'default'

### ISSUE THREAD

**Issue by jercle** [oclif/oclif.github.io#157]
Issue with docs: https://github.com/oclif/oclif.github.io/blob/docs/docs/base_class.md

Copying the code from the above, I get the following error:
`Property 'flags' does not exist on type 'default'. Did you mean to access the static member 'default.flags' instead?`

Is it possible to modify the flags within the init() of the base class?

**Comment by mdonnalley** [comment]
That page has been updated since you opened this issue. Please reopen if you're still having trouble. Thanks!
