### ISSUE TITLE
The CLI Flags Explained links to 'Page Not Found'

### ISSUE THREAD

**Issue by kurtaking** [oclif/oclif.github.io#241]
I was reading through the docs and noticed the following link takes you to a **Page Not Found** page.

https://github.com/oclif/oclif.github.io/blob/1f455a0245dc466ded2d33792bd592f085155b19/docs/flags.md?plain=1#L162

**Comment by kurtaking** [comment]
Found the article - https://oclif.io/blog/2019/02/20/cli-flags-explained

**Comment by mdonnalley** [comment]
@kurtaking I'm not seeing it link to a non-existent page on my end.

<img width="654" alt="Screenshot 2024-04-15 at 8 44 18 AM" src="https://github.com/oclif/oclif.github.io/assets/10244328/08946490-da83-4178-940d-296e997eb27f">

What link does it try to take you to?

**Comment by kurtaking** [comment]
Hey @mdonnalley, I went to capture a screen recording and it's working for me as well. I'm not sure why it didn't work for me yesterday. 🤷🏼 Thanks for the swift response.

**Comment by kurtaking** [comment]
p.s. - I'm noticing the docs are being updated and saw the spring 2024 update. 🎉 ❤️ it's great to see oclif getting some attention.
