### ISSUE TITLE
cli.action.start params

### ISSUE THREAD

**Issue by justin-barca** [oclif/oclif.github.io#71]
the cli-ux action.start has a different function signature than the one listed.  See their readme which reads 
```
// show on stdout instead of stderr
cli.action.start('starting a process', 'initializing', {stdout: true})
```

**Comment by RasPhilCo** [comment]
Closed via https://github.com/oclif/oclif.github.io/commit/98a93d894d21bcc49426a1d000f0a5b4c97f8a94
