### ISSUE TITLE
Do you have any sample code where flags are non static?

### ISSUE THREAD

**Issue by denizoguz** [oclif/oclif.github.io#99]
Lots of my commands share the same code and set of flags with minor differences. I want to able to define flags in my base class and just override it in some of super classes. 
Instead of: **_const {flags} = this.parse(Get)_** I want to write something like **_const {flags} = this.parse(this.getFlags()}_**. Command classes will sometimes override getFlags() method inherited from base class.  I have tried it but I couldn't get rid of all Typescript problems. 
Thanks for any help.

**Comment by RasPhilCo** [comment]
We've done something akin to:

```
class Foo extends Base {

static flags = {
  ...Base.flags,
  <overridden flags defined here>
  }

...
}
```

**Comment by mdonnalley** [comment]
See https://oclif.io/docs/base_class
